language: python
sudo: false
dist: trusty

python:
  - "3.6"

# whitelist
branches:
    only:
        - master
        - develop

# install python dependencies
install:
  - pip install codecov
  - pip install --upgrade pytest
  - pip install pytest-cov
  - pip install numpy
  - pip install -e .

# run tests
script: 
  - py.test --cov src/datreant

after_success:
  - codecov
